src/distrs/norm.jl

Thereby also fix bug in `normlogpdf` for non `Float64` arguments causing it to call normpdf instead of normlogpdf.
I don't think we should force all inputs to end up as `Float64`s. We should only make this restriction in the inner algorithms where we have to use the precision of the floating point number.
I wanted to look into the potential cancellation error in https://github.com/JuliaStats/Distributions.jl/blob/a4568d75baa797498983ded6a1e8f0442e326b7a/src/univariate/continuous/lognormal.jl#L56 and found the bug here, but even it hadn't been there, I would just have received the `Float64` result.

Loosen signature of functions in norm.jl from Float64 to Real whenever possible

---

src/distrs/norm.jl

Following the discussion in https://github.com/JuliaStats/Distributions.jl/issues/423, don't be too picky about the input types to these functions, just duck type it. This allows for AD. I left the restrictions to Real on the distribution parameters (for now)
CC @scidom @jrevels

relax restriction to Real input (allows for automatic differentiation)

---

src/basicfuns.jl
src/distrs/beta.jl
src/distrs/norm.jl
test/rmath.jl

Use erfcinv to compute the quantiles of the normal distribution.
Fixes https://github.com/JuliaStats/Distributions.jl/issues/516

Only convert back to input type for Float16 and Float32 in the quantile function for the normal distribution.

---

REQUIRE
src/StatsFuns.jl
src/basicfuns.jl
test/basicfuns.jl

Requires https://github.com/JuliaLang/Compat.jl/pull/280 and a new `Compat` tag.

Fix depwarn on 0.6 due to vectorized functions

---

src/basicfuns.jl
test/basicfuns.jl

This version avoids the `Inf-Inf` errors which (incorrectly) resulted in
`NaN`s before, and also takes care to pass through actual `NaN`s.
New tests for both vector and bivariate forms.
Fixes #22.

Added handling of Infs and NaNs to logsumexp, with tests.

---

.travis.yml
src/basicfuns.jl
src/distrs/pois.jl
src/misc.jl
test/basicfuns.jl
test/rmath.jl
test/runtests.jl

My purpose in creating an explicit `BigInt` method for `lstirling_asym` was to get full accuracy on small integer values of `x` from the `Float64` and `Float32` methods by evaluating `log(factorial(x-1))` explicitly and storing these in an array.  The only downside I can see to this is that the function will be a bit discontinuous at these small integer values (perhaps literally a bit or two of discontinuity).
This way the Stirling error function `stirlerr(n)` in #33 can be replaced by `lstirling_asym(n + 1)`

Add doc strings and explicit BigInt method for lstirling_asym.

---

src/basicfuns.jl
src/misc.jl

Need to double the backslashes in math expressions.  Julia v0.6 is okay with the single backslashes but v0.7.0-DEV complains about unknown escape sequences.

Double backslashes in math expressions

---

src/StatsFuns.jl
src/basicfuns.jl
test/basicfuns.jl

This uses Julia's reduction functionality to improve the `logsumexp`
functionality. It no longer relies on 1-based indexing, is fast
on CuArrays, and there is now a generic fallback for iterable collections.
I've also renamed the 2-arg `logsumexp` to `logaddexp`, since Julia
convention is to use different functions for reductions and
reducers (e.g. `max` vs `maximum`).

Write logsumexp in a more generic form

---

src/rmath.jl

Fixes https://github.com/JuliaStats/StatsFuns.jl/issues/64

Restrict rmath `ccall` parameters to `Union{Float64, Int}`

---

.appveyor.yml
.travis.yml
Project.toml
REQUIRE
src/distrs/beta.jl
src/distrs/binom.jl
src/distrs/chisq.jl
src/distrs/fdist.jl
src/distrs/gamma.jl
src/distrs/pois.jl
src/distrs/tdist.jl
src/misc.jl
test/REQUIRE
test/misc.jl

Supersedes #76. Regarding the changes to the `logmvgamma` tests, the old version didn't compute what the docstring claimed. Fixing the issue required changing the tests.

Upgrade to Project file and to SpecialFunctions 0.8

---

src/basicfuns.jl

This PR request fixes the initial value for `reduce` in `logsumexp`. This error was discovered in the following [issue](https://github.com/TuringLang/Turing.jl/issues/1017#issuecomment-563128527) in Turing (see final comment).

Fixes initial value for reduce in logsumexp

---

README.md

Users are often confused by this.
We could even stop exporting these functions and/or move them to Distributions.

Point to Distributions.jl

---

src/rmath.jl

`α` and `β` do not match the parameterization that we actually, and these names were inconsistent with the generic method.
Fixes #92.

Fix `gamma` argument names

---

src/basicfuns.jl
test/basicfuns.jl

Change the logistic function to increase accuracy for subnormal values (e.g. `logistic(-740.0)`). See [my notes](https://github.com/johnmyleswhite/StatsFunctionsNotes/blob/master/A%20Numerically%20Accurate%20Inverse%20Logit%20Function%20for%2064-Bit%20Floating%20Point.ipynb) for extended details.

Improve accuracy of logistic

---

.appveyor.yml
.travis.yml

Addresses https://github.com/JuliaStats/StatsFuns.jl/pull/97#pullrequestreview-465192954.
Currently, StatsFuns is tested with Julia 1.3, stable, and nightly on AppVeyor and Julia 1.0, 1.3, and nightly on Travis. With this PR the package is tested with Julia 1.0, stable, and nightly on both AppVeyor and Travis.

Run CI tests on Julia LTS, stable, and nightly

---

src/basicfuns.jl
test/basicfuns.jl

This PR fixes https://github.com/JuliaStats/StatsFuns.jl/issues/91.
I used the streaming algorithm for the computation of logsumexp described in http://www.nowozin.net/sebastian/blog/streaming-log-sum-exp-computation.html in one of my projects lately, and I noticed that there is already an open issue for adding it to StatsFuns.
I reran the benchmark mentioned in the issue and got:
```julia
julia> using StatsFuns, BenchmarkTools, Random
julia> Random.seed!(100);
julia> n = 10_000_000;
julia> X = 500 .* randn(n);
julia> @btime logsumexp($X)
94.999 ms (0 allocations: 0 bytes)
2697.6523838563817
julia> @btime StatsFuns.logsumexp_onepass($X)
32.815 ms (0 allocations: 0 bytes)
2697.6523838563817
julia> f(X) = reduce(logaddexp, X)
f (generic function with 1 method)
julia> @btime f($X)
162.519 ms …
```

Add onepass algorithm for logsumexp

---

.github/workflows/CompatHelper.yml

Turns out the official CompatHelper workflow in CompatHelper.jl contained a bug (https://github.com/JuliaRegistries/CompatHelper.jl/pull/376). It seems everything will become easier soon with compathelper-action (https://github.com/JuliaRegistries/CompatHelper.jl/pull/379).

Fix CompatHelper.yml

---

Project.toml
src/StatsFuns.jl
src/inverse.jl
test/inverse.jl
test/runtests.jl

Required to support JuliaGaussianProcesses/GPLikelihoods.jl#52.

Support InverseFunctions where applicable

---

.github/workflows/IntegrationTest.yml
.github/workflows/ci.yml
README.md

This PR updates the Github actions setup and cancels runs for all but the latest commit in each PR automatically. I think this is particularly useful for the more time consuming integration tests. Additionally, coverage upload issues don't affect the status of the jobs anymore.

Cancel Github actions for previous commits in PRs

---

Project.toml
src/distrs/norm.jl
test/rmath.jl

Currently these functions compute `erfcinv` in possibly lower precision and only take into account the parameters (and their types) of the normal distribution afterwards. This PR fixes and tests this problem.

Promote arguments of `norminvcdf` and `norminvccdf`

---

Project.toml
src/distrs/beta.jl
src/distrs/binom.jl
src/distrs/chisq.jl
src/distrs/fdist.jl
src/distrs/gamma.jl
src/distrs/pois.jl
src/distrs/tdist.jl
test/rmath.jl

I think we should begin to use Julia implementations when they are available. There is is really no need to call out to Rmath when we have implementations available. Eventually, we should then also be able to drop Rmath as a package dependency and just use it for testing although there is still some work to do. However, SpecialFunctions now has some of the more tricky functions available so we can get quite far. This has a conflict with https://github.com/JuliaStats/StatsFuns.jl/pull/112 so it would be good to get than one merged first and I can update this PR afterwards.

Use julia implementations for pdfs and some cdf-like functions

---

src/StatsFuns.jl
src/tvpack.jl
test/runtests.jl
test/tvpack.jl

This reincludes the `tvpack.jl` file with the bivariate normal CDF function. I've added a `bvncdf(x,y,r)` function that corresponds to the standard normal cdf `Φ(x,y;ρ)` where `r=ρ`. The function also handles `Inf` and `-Inf`  arguments correctly now.

include tvpack.jl with bivariate normal cdf

---

.github/workflows/ci.yml
Project.toml
src/distrs/beta.jl
src/distrs/binom.jl
src/distrs/chisq.jl
src/distrs/fdist.jl
src/distrs/gamma.jl
src/distrs/pois.jl
src/distrs/tdist.jl
test/misc.jl
test/rmath.jl

Fix Julia 1.0 compatibility by reverting https://github.com/JuliaStats/StatsFuns.jl/pull/113 and fixing some test tolerances.
I don't think there is a good way to fix Julia 1.0 compatibility without reverting that PR since only SpecialFunctions 0.8 supports Julia 1.0 but many fixes in more recent SpecialFunctions versions are required. E.g., `gamma_inc_inv` contains an undefined variable `r` in SpecialFunctions 0.8, i.e., fixing this problem would require us to reimplement `gamma_inc_inv` in StatsFuns.
#113 will be reapplied and released as part of StatsFuns 0.10.0 for Julia >= 1.3 and recent versions of SpecialFunctions.
Fixes #136.

Fix Julia 1.0 compatibility

---

.github/workflows/ci.yml
Project.toml
src/StatsFuns.jl
src/distrs/beta.jl
src/distrs/binom.jl
src/distrs/chisq.jl
src/distrs/fdist.jl
src/distrs/gamma.jl
src/distrs/pois.jl
src/distrs/tdist.jl
test/rmath.jl

This PR is a cleaned and corrected version of #139. Copied from there:
> This PR is a follow-up to https://github.com/JuliaStats/StatsFuns.jl/pull/138 and reapplies https://github.com/JuliaStats/StatsFuns.jl/pull/113. It updates the compat entries and tests the oldest supported Julia version + LTS to ensure that users don't end up with (major) regressions compared with StatsFuns 0.9.17 that uses Rmath instead of Julia implementations of these functions.

Reapply #113 and prepare release of StatsFuns 1.0.0

---

src/distrs/tdist.jl

Today I realized that
1. I already implemented a pure Julia version of the F-distribution functions
2. We can just implement the `T(ν)`-distribution via the `F(1,ν)`-distribution 
Hence this PR. This is an alternative to #147

Implement the T-distribution via the F-distribution

---

src/distrs/gamma.jl
test/misc.jl

After the native Julia implementation for the Gamma distribution was implemented, HypergeometricFunctions added the _₁F₁ function which will decide on the algorithm based on the arguments. This ensures good behavior in a broader part of the parameter space.
Fixes https://github.com/JuliaStats/StatsFuns.jl/issues/150

Use _₁F₁ instead of drummond1F1 in gammalogcdf

---

Project.toml
src/distrs/beta.jl
test/misc.jl
test/rmath.jl

Fix #154 by handling degenerate beta distributions in quantile functions.
To make it clearer and more consistent I also added cases for the degenerate beta distribution with zero beta parameter to the other functions; currently we rely on how SpecialFunctions handles these degenerate cases.

Fix quantiles of degenerate beta distributions

---

test/misc.jl
test/rmath.jl

I think this has been wrong from the beginning but just happened to work until Julia 1.10.
There are failures on Julia 1.6 related to inference. I've identified the regression to come from version 0.3.18 of `HypergeometricFunctions`. It's not at all clear why it happens and `Base.return_types` and `code_warntype` disagrees
```julia
julia> Base.return_types(betalogcdf, (Rational{Int}, Rational{Int}, Rational{Int}))
1-element Vector{Any}:
Any
julia> code_warntype(betalogcdf, (Rational{Int}, Rational{Int}, Rational{Int}))
Variables
#self#::Core.Const(StatsFuns.betalogcdf)
α::Rational{Int64}
β::Rational{Int64}
x::Rational{Int64}
@_5::Int64
q::Float64
p::Float64
_x::Rational{Int64}
Body::Float64
...
```
not clear what we should do here.

Use promote_type instead of promote_eltype in misc tests

---

.github/dependabot.yml
.github/workflows/IntegrationTest.yml
.github/workflows/ci.yml

The PR updates the version of the GH actions (which allows us to use eg `min` and `lts` to specify Julia versions), runs tests on the latest pre-release instead of nightly (supposedly to give more relevant and stable results), and adds a dependabot config.

Update GH actions and add dependabot

---

src/StatsFuns.jl
src/distrs/signrank.jl
src/rmath.jl
test/rmath.jl

Implementation of the signrank distribution.
The `cdf` is heavily optimized, since that is what is needed for the popular hypothesis test associated with this distribution.
The testing in this package seems quite involved, I could use some pointers on where to add the tests.
```jl
using StatsFuns
using Rmath
signrankpdf.(-2:12,4)
dsignrank.(-2:12,4,false)
signranklogpdf.(-2:12,4)
dsignrank.(-2:12,4,true)
signrankcdf.(-2:12,4)
psignrank.(-2:12,4,true,false)
signranklogcdf.(-2:12,4)
psignrank.(-2:12,4,true,true)
signrankccdf.(-2:12,4)
psignrank.(-2:12,4,false,false)
signranklogccdf.(-2:12,4)
psignrank.(-2:12,4,false,true)
signrankinvcdf.(-0.01:0.01:1.01,4)
qsignrank.(-0.01:0.01:1.01,4,true,false)
signrankinvcdf.(0.0624,4)
signrankinvcdf.(0.0625,4)
signrankinvcdf.(0.0626,4) …
```

add signrank distribution

---

.github/workflows/IntegrationTest.yml

Now that signrank and wilcox distributions are about to be released, it will become possible to replace the Rmath versions in HypothesisTests with these Julia functions. Hence it might be interesting/more relevant to also run downstream tests with HypothesisTests.
Additionally, due to a discussion with @andreasnoack I started to wonder whether it would be better to run downstream tests with the latest released versions of the downstream packages instead of the development branch. One could argue that downstream packages are responsible for testing their development versions appropriately, and its our main responsibility in StatsFuns to not break user code, ie not break compatibility with existing releases.

Add downstream tests of HypothesisTests

---

.git-blame-ignore-revs

Adds a `.git-blame-ignore-revs` file such that https://github.com/JuliaStats/StatsFuns.jl/commit/e9ae0ee56eec19bcfa489b4cc5e136889a26169d is hidden from git-blame, in the Github web interface and with the corresponding setting also locally, see e.g. https://github.com/fredrikekre/Runic.jl?tab=readme-ov-file#ignore-formatting-commits-in-git-blame.

Hide formatting commit in git-blame

---

Project.toml
src/distrs/wilcox.jl

Löffler published a simpler recurrence relation for the number of partitions in the Wilcox distribution: https://upload.wikimedia.org/wikipedia/commons/f/f5/LoefflerWilcoxonMannWhitneyTest.pdf
This reduces computation time and memory allocations.
```julia
julia> using StatsFuns, Chairmarks
julia> @be StatsFuns.wilcoxpdf.(1, 1, 0:1)
Benchmark: 6595 samples with 169 evaluations
min    53.006 ns (6 allocs: 272 bytes)
median 60.160 ns (6 allocs: 272 bytes)
mean   78.120 ns (6 allocs: 272 bytes, 0.32% gc time)
max    6.206 μs (6 allocs: 272 bytes, 97.99% gc time)
julia> @be StatsFuns.wilcoxpdf.(10, 20, 0:200)
Benchmark: 96 samples with 1 evaluation
min    866.500 μs (583 allocs: 1.663 MiB)
median 931.500 μs (583 allocs: 1.663 MiB)
mean   1.042 ms (583 allocs: 1.663 MiB, 5.01% gc time)
max …
```

Use Löffler's recurrence relation for the Wilcox distribution
